n = input('Digite algo: ')
print('O tipo primitivo desse valor eh ', type(n))
print('so tem espacos?', n.isspace())
print('Eh alfabetico?', n.isalpha())
print('Eh alfanumerico?', n.isalnum())
print('Eh numerico?', n.isnumeric())
print('Esta em minusculo?', n.islower())
print('Esta em maiuscula?', n.isupper())
print('Esta capitalizada?', n.istitle())
